// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbMUdrQDyptmQ2hH-GoGpZ0XdtSTcW6o4',
    appId: '1:321041611091:web:d93fa660c5e7cb22c889a6',
    messagingSenderId: '321041611091',
    projectId: 'blueberry-build-test-d443e',
    authDomain: 'blueberry-build-test-d443e.firebaseapp.com',
    storageBucket: 'blueberry-build-test-d443e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFnRYeB0198DGcxcwinWjty9GnkJa9G0A',
    appId: '1:321041611091:android:04b765ee4c2f7fe3c889a6',
    messagingSenderId: '321041611091',
    projectId: 'blueberry-build-test-d443e',
    storageBucket: 'blueberry-build-test-d443e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACi_1hiY8-W4afnAwvLYaumCTSRSVLOzg',
    appId: '1:321041611091:ios:3e1a3d958e829496c889a6',
    messagingSenderId: '321041611091',
    projectId: 'blueberry-build-test-d443e',
    storageBucket: 'blueberry-build-test-d443e.appspot.com',
    iosBundleId: 'com.example.blueberry',
  );
}
