// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVzMOPoTeNZPv0VRdZsILerFFECDFSzq4',
    appId: '1:274880747730:web:56a18b0089fbb3d29eb50b',
    messagingSenderId: '274880747730',
    projectId: 'blueberrytemplate-2024-summer',
    authDomain: 'blueberrytemplate-2024-summer.firebaseapp.com',
    storageBucket: 'blueberrytemplate-2024-summer.appspot.com',
    measurementId: 'G-MSJGFSH464',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJWO7fIJQBndQIgN-VWyllEjqh6t6lBh4',
    appId: '1:274880747730:android:95c3a117fc470aa19eb50b',
    messagingSenderId: '274880747730',
    projectId: 'blueberrytemplate-2024-summer',
    storageBucket: 'blueberrytemplate-2024-summer.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAypAgggU745jI4yaJB9Hz_980JjD6T4o',
    appId: '1:274880747730:ios:11f0fb88a7ce46e79eb50b',
    messagingSenderId: '274880747730',
    projectId: 'blueberrytemplate-2024-summer',
    storageBucket: 'blueberrytemplate-2024-summer.appspot.com',
    iosClientId: '274880747730-k5h3ijrilmvhj7bvmskgui0ocvr9n4i0.apps.googleusercontent.com',
    iosBundleId: 'com.example.blueberry',
  );
}
