name: Flutter Code Analysis

on: [ pull_request, push ]

jobs:
  analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: stable
      - name: Install dependencies
        run: flutter pub get
      - name: Run analysis
        run: flutter analyze --machine
      - name: Upload analysis results (optional)
        uses: actions/upload-artifact@v3
        with:
          name: analysis-results
          path: build/flutter_analyze_results.json
